

services:
  postgres:
    image: postgres:17
    environment:
      POSTGRES_PASSWORD: 123
      POSTGRES_USER: postgres
      POSTGRES_DB: TesteLazaro
    ports:
      - "5433:5432"
    volumes:
      - ./script.sql:/docker-entrypoint-initdb.d/Script.sql
  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/TesteLazaro
    ports:
      - "8080:8080"
    depends_on:
      - postgres
  
    
 
   