
FROM maven:3.9.3-eclipse-temurin-17 AS build
WORKDIR /app
COPY pom.xml mvnw ./
COPY src ./src
RUN chmod +x mvnw
RUN ./mvnw clean package -DskipTests



FROM openjdk:25-ea-jdk
WORKDIR /app
COPY target/*.jar app.jar
EXPOSE 8080
ENTRYPOINT ["java", "-jar", "app.jar"]
